server:
  port: 0
spring:
  application:
    name: luminoso-candidate-management
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/dev
          public-key-location: client.pub
  zipkin:
    service:
      name: ${spring.application.name}
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  liquibase:
    change-log: classpath:/db/liquidbase-changelog.xml
keycloak:
  realm: dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: ${spring.application.name}
  credentials:
    secret: 53bc798a-0fc3-4000-b1bf-12f26642ab6a
  public-client: false
  verify-token-audience: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG
      keycloak: DEBUG
      apache:
        catalina: DEBUG