server:
  port: 0
  http2:
    enabled: true
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.jks
    key-password: password
    key-alias: jwt
    key-store-password: password
spring:
  application:
    name: authorization
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
      enabled: true
  sleuth:
    async:
      enabled: false
  zipkin:
    enabled: false
    service:
      name: ${spring.application.name}
  rabbitmq:
    username: admin
    password: g*34%zHwQQ#9
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 777117467633-eef86h9kmkg4gvh8q3631d2m3j67q6nk.apps.googleusercontent.com
            clientSecret: UF-PaKRI8tkECGbRfvK7DonJ
            scope:
              - email
              - profile
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/master
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/liquidbase-changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG
