server:
  port: 0
spring:
  application:
    name: messages
  data:
    mongodb:
      port: 27017
      database: luminoso
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/soullabs
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}