version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672
#  keycloak:
#    image: jboss/keycloak:8.0.1
#    restart: on-failure
#    ports:
#      - "9999:8080"
#    environment:
#      KEYCLOAK_IMPORT: /tmp/luminoso-realm.json
#      KEYCLOAK_USER: admin@luminoso.com
#      KEYCLOAK_PASSWORD: 2%hDtyKq4Y9h
#      DB_VENDOR: postgres
#      DB_ADDR: keycloak-db
#      DB_USER: admin
#      DB_PASSWORD: admin
#    depends_on:
#      - keycloak-db
#    volumes:
#      - "./keycloak/themes:/opt/jboss/keycloak/themes"
#      - "./keycloak/realms/luminoso-realm.json:/tmp/luminoso-realm.json"
  authorization:
    build: ./authorization
    restart: on-failure
    ports:
      - 5005:5005
      - 9999:8443
    depends_on:
      - gateway
      - rabbitmq
      - discovery-service
      - zipkin
  authorization-db:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    ports:
      - 5433:5432
    volumes:
      - ./pgdata/authorization:/var/lib/postgresql/data
  zipkin:
    image: openzipkin/zipkin:2.19
    restart: on-failure
    environment:
      STORAGE_TYPE: mem
      JAVA_OPTS: -Dlogging.level.zipkin=DEBUG
    ports:
      - 9411:9411
  tcs:
    build: ./tcs
    restart: on-failure
    depends_on:
      - gateway
      - discovery-service
      - tcs-db
  tcs-db:
    image: redis:5.0.7
    restart: on-failure
    ports:
      - 6379:6379
  discovery-service:
    image: consul:1.6.2
    restart: on-failure
    ports:
      - 8500:8500
  gateway:
    build: ./gateway
    restart: on-failure
    ports:
      - 1000:1000
    depends_on:
      - discovery-service
  users-management:
    build: ./users-management
    restart: on-failure
    ports:
       - 5005:5005
    depends_on:
      - gateway
      - authorization
      - rabbitmq
      - tcs
      - discovery-service
      - zipkin
  users-management-db:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    ports:
      - 5434:5432
    volumes:
      - ./pgdata/users-management:/var/lib/postgresql/data
  candidate-management:
    build: ./candidate-management
    restart: on-failure
    depends_on:
      - gateway
      - authorization
      - tcs
      - zipkin
      - discovery-service
      - candidate-management-db
  candidate-management-db:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    ports:
      - 5435:5432
    volumes:
      - ./pgdata/candidate-management:/var/lib/postgresql/data
  website-management:
    build: ./candidate-management
    restart: on-failure
    depends_on:
      - gateway
      - authorization
      - discovery-service
      - tcs
      - zipkin
      - website-management-db
  website-management-db:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    ports:
      - 5436:5432
    volumes:
      - ./pgdata/candidate-management:/var/lib/postgresql/data

