server:
  port: 0
spring:
  application:
    name: analytics
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:1000/authorization/.well-known/jwks.json
          issuer-uri: http://authorization:1000/authorization
        apiKey:
          client-id: 19828b9c-61aa-4288-8644-fc890187c71e
          client-secret: e6d5957f3a254bae2d05f31617d94dc68559431c50d3f1ffbf3136b2b5cbfcc7
          introspection-uri: http://authorization:1000/authorization/oauth/apikey/introspect
  zipkin:
    base-url: http://zipkin:9411
    service:
      name: ${spring.application.name}
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://analytics-db:5432/master
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/liquidbase-changelog.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG
      keycloak: DEBUG
      apache:
        catalina: DEBUG
