server:
  port: 1000
spring:
  application:
    name: luminoso-gateway
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  zipkin:
    service:
      name: ${spring.application.name}
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework: DEBUG