server:
  port: 0
spring:
  application:
    name: content-delivery-service
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:8080/auth/realms/dev/protocol/openid-connect/certs
          issuer-uri: http://authorization:8080/auth/realms/dev
          public-key-location: client.pub
  zipkin:
    service:
      name: ${spring.application.name}
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG
      keycloak: DEBUG
      apache:
        catalina: DEBUG