server:
  port: 0
spring:
  application:
    name: luminoso-communications
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/soullabs/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8080/auth/realms/soullabs
          public-key-location: client.pub
  zipkin:
    base-url: http://zipkin:9411
    service:
      name: ${spring.application.name}
    enabled: false
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 0cda70a51c3d09 # Requires creds
    password: c8da9c4805a6d8
keycloak:
  realm: dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: luminoso-communications
  credentials:
    secret: b776e4d6-d686-48cc-bf9f-56bd214a6941
  public-client: false
  verify-token-audience: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG