server:
  port: 0
spring:
  application:
    name: luminoso-real-estate
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
  zipkin:
    service:
      name: ${spring.application.name}
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  liquibase:
    change-log: classpath:/db/liquidbase-changelog.xml
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8989/oauth/token
      user-authorization-uri: http://localhost:8989/oauth/authorize
      client-id: a6fc4516-6d8c-4996-bb00-34129ccb089a
      client-secret: 32F88BDCCE10F9E5F62476F3BB439DC4BFE727AB65D7400E94722AF433F9B84F
    resource:
      token-info-uri: http://localhost:8989/oauth/check_token
#      jwt:
#        key-value: ${JWT_PUBLIC_KEY_VALUE}
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG